/**
 * @author Kavya Patel
 */

let messages = {
    InvalidRegisterDetails: "Please provide the same email address and contact number",
    VerificationCodeSentToBoth: "Your account has been created. Please provide security code sent to your email address and contact number",
    InvalidCredentials: 'Account does not exists',
    internalServerError: 'Internal server error. Please try after some time',
    InvalidDetails: 'Please provide valid details',
    InvalidVerificationCode: 'Please provide a valid OTP',
    VerificationSuccess: 'Account verified successfully',
    Success: 'Success',
    TOKEN_NOT_PROVIDED: 'Your login session seems to be expired. Please login again',
    InvalidPassword: 'Please provide valid password',
    LoginSuccess: 'Logged in successfully',
    LogoutSuccess: 'Logged out successfully',
    ProfileUpdated: 'Profile updated successfully',
    ResetPasswordMailSent: 'Please check your registered email for further',
    PasswordUpdateSuccess: "Password updated successfully",
    ResetPasswordLinkExpired: "Your reset password link seems to be expired",
    EmailAlreadyExists: 'Email id already exists',
    EmailResetSuccessful: 'Email address updated successfully',
    ContactNumberAlreadyExists: 'Contact number already exists',
    ContactResetSuccessful: 'Contact number updated successfully',
    CMSPageNotFound: "CMS page does not exist",
    NotificationStatusUpdated: 'Notifications marked as read',
    InvalidTicketDetails: "Ticket does not exists",
    MultipleActivitiesRemoved: 'Activities removed successfully',
    SingleActivityRemoved: 'Activity removed successfully',
    MailSent: "Mail sent successfully",
    EmailChangeVerificationSent: 'One time password has been sent to your registered email address',
    ContactChangeVerificationSent: 'One time password has been sent to your registered contact number',
    OldPasswordNotMatch: "Please provide valid old password",
    MasterNotFound: 'Details does not exists',
    ProjectCreatedSuccess: 'Project created successfully',
    ProjectNotFound: 'Project does not exists',
    ProjectUpdatedSuccess: 'Project details updated successfully',
    UpdatingProjectNotAllowed: 'You are not authorized to update these details. Only initiator can do it',
    AddingPackageNotAllowed: 'You are not authorized to add package. Only initiator can do it',
    PackageAddedSuccess: 'Package created successfully',
    PackageUpdatedSuccess: 'Package details updated successfully',
    SkillNotFound: "Skill does not exist",
    SkillRemoved: 'Skill removed successfully',
    SkillCreatedSuccess: 'Skills added successfully',
    EmploymentCreatedSuccess: 'Employment details added successfully',
    ProjectRemoved: 'Project removed successfully',
    EmployNotFound: "Employment details does not exists",
    EducationNotFound: "Education details does not exists",
    EducationCreatedSuccess: 'Education details added successfully',
    EmploymentUpdatedSuccess: 'Employment details updated successfully',
    EducationUpdatedSuccess: 'Education details updated successfully',
    PortfolioCreatedSuccess: 'Project added successfully',
    InvitationMailSent: 'Invitation sent successfully',
    PackageNotFound: 'Package does not exists',
    JoinPackageRequestAdded: 'Your package joining request has been sent successfully',
    JoinRequestAlreadyExists: 'Your request for joining this package already exists',
    CollaboratorNotFound: "Collaborator does not exists",
    JoinRequestStatusUpdateNotAllowed: 'You are not authorized to for this action. Only initiator can do it',
    UserRequestAccepted: 'Request accepted successfully',
    UserRequestRejected: 'Request rejected successfully',
    TicketUpdated: 'Ticket updated successfully',
    TicketAlreadyExists: 'Ticket already exists. Please try updating it or provide another name',
    TicketCreatedSuccess: 'Your support request has been created successfully',
    TicketNotFound: "Support ticket does not exists",
    CommentSuccess: "Your comment has been submitted successfully",
    ContactUsQuerySent: "Your query has been sent successfully",
    EmploymentDeletedSuccess: "Employment details removed successfully",
    EducationDeletedSuccess: "Education details removed successfully",
    StartWorkNotAllowed: "You are not authorized to start work",
    WorkStarted: 'Your work process started successfully',
    SubmitWorkNotAllowed: "You are not authorized to submit work",
    WorkSubmitted: "Your submission request has been sent successfully",
    WorkProgressNotFound: "Work has not been started yet by any collaborator",
    SubmissionStatusNotValid: "Please provide valid submission status. You can either accept or reject it",
    SubmissionApproved: "Submission approved successfully",
    SubmissionRejected: "Submission rejected successfully",
    FinishPackageNotAllowed: "This package cannot be finished until all the submissions are approved",
    PackageFinished: "Package completed successfully",
    FinishProjectNotAllowed: "This project cannot be finished until all the projects are completed",
    ProjectCompleted: "Project completed successfully",
    WithdrawPackageSuccess: 'Your work has been withdrawn successfully'

}

let codes = {
    FRBDN: 403,
    INTRNLSRVR: 500,
    Success: 200,
    DataNotFound: 404,
    BadRequest: 400,
    ReqTimeOut: 408
}

module.exports = {
    CODE: codes,
    MESSAGE: messages
}